name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Django DB
      env:
        DB_NAME: mydb
        DB_USER: myuser
        DB_PASSWORD: mypassword
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        SECRET_KEY: testkey
        DEBUG: false
      run: |
        python manage.py migrate

    - name: Run tests
      env:
        DB_NAME: mydb
        DB_USER: myuser
        DB_PASSWORD: mypassword
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        SECRET_KEY: testkey
        DEBUG: false
      run: |
        python manage.py test
